### ISSUE TITLE
Undefined control sequence \bit and \byte

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#100]
[Anonymous report]

There seems to be an issue with `\bit` and `\byte`. The manual reads "The units `\bit` and `\byte` are also available", but the following code does not compile:

```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
Reference output: $ 123\,\mathrm{b} $
siunitx output: \SI{123}{\bit}
\end{document}
```

(using pdfTeX, Version 3.1415926-1.40.9 (MiKTeX 2.7), Package: siunitx 2010/11/05 v2.1b)

```
//! Undefined control sequence.
<argument> \bit
l.8 siunitx output: \SI{123}{\bit}                   
? q
OK, entering \batchmode...
! Undefined control sequence.
<argument> \bit
l.8 siunitx output: \SI{123}{\bit}//
```

Or does the problem sit in front of the PC?

**Comment by timlg07** [comment]
Alternatively you can use `\usepackage[binary-units=true]{siunitx}` which is working fine in my case, while using `\sisetup` isn't.

**Comment by ipatrol** [comment]
Can you fix the documentation to reflect this?

**Comment by josephwright** [comment]
> Can you fix the documentation to reflect this?

I'm not sure what you mean

**Comment by muelli** [comment]
I've pulled my hair out making `\byte` work. Grepping through the documentation finds "Binary data is expressed in units of bits and bytes. These are normally givenbit
byte prefixes which use powers of two, rather than the powers of ten used by the si prefixes.
As these binary prefixes are closely related to the si prefixes, they are defined by siunitx"

A sentence like "in order to load \bit and \byte load the package with binary-units=true, e.g. `\usepackage[binary-units=true]{siunitx}`" would have helped me to make it work more quickly.

**Comment by muelli** [comment]
oh, thanks for the clarification and sorry for the noise. (yeah, I should upgrade my system...)
