### ISSUE TITLE
Rounding with uncertainties

### ISSUE THREAD

**Issue by josephwright** [josephwright/siunitx#179]
[Reported by [Michael Forbes](https://bitbucket.org/mforbes)]

Presently `siunitx` does not apply rounding when there is an uncertainty specified. It would be useful if `round-mode=figures,round-precision=2` could be used to round the uncertainties (and consequently the numbers).

I.e:

```
(1.234567+-0.03397392) -> 1.235(34)

(1.234567+-0.339792) -> 1.23(34)
```

Michael.

**Comment by Legion2017** [comment]
I came across the same thing and like Micheal Forbes its aboout the output of a fitting algortihm. Unfortunately the program I have to use generates varying numbers of digits for both, the mean and the uncertainties. Because I have lots of date I usually just copy and paste it into my document. Therefore it would be a nice feature if siunitx would round at least the mean.

MWE:
```
\documentclass{article}

\usepackage{siunitx}
\sisetup{%
round-mode=places,
round-precision=2,
separate-uncertainty=true,
}

\begin{document} \parindent 0pt
It is:\\
\num{102,506000}\\
\num{102,506000+-1,966940}\\

It should be:\\
\num{102,51+-1,97}

\end{document}
```

**Comment by Jellby** [comment]
A "trivial" improvement would be to enable rounding if ``omit-uncertainty`` is false, at least.

**Comment by josephwright** [comment]
I'm going to look at this for v3

**Comment by josephwright** [comment]
I've added `drop-uncertainty` is a968758943e06b2943fe5a3bf08251686011db99: that deals with the 'just ignore the uncertainty' part. Rounding using uncertainty values, at least in a basic form, is sorted 'in my mind' so will be available shortly.

**Comment by alexseuthe** [comment]
Hi, @josephwright do you know when rounding with uncertainties will be available?

**Comment by josephwright** [comment]
Er, depends on other projects. Hopefully this year!

**Comment by krono** [comment]
Hey, @josephwright 

I just want to give a datapoint where this can be useful.

I report means of n time measurements with a 95% confidence interval, the latter of which I inteded to report with a ±.

However, the data generated from my source are a bit unfriendly:
```
A & 126.9471839 +- 0.4533629021353263 \\
B & 3014.2006023000004 +- 35.49527970590613 \\
C & 115.9 +- 1.8911537669917304 \\
D & 2859.9 +- 31.740948320720445 \\
E & 4560.4 +- 216.22856848154723 \\
F & 310.23089999999996 +- 2.989537980737702 \\
G & 11552.643399999999 +- 43.95669988980899 \\
H & 4135.6639000000005 +- 8.242421115864909 \\
I & 4087.1410603000004 +- 106.40865059994294 \\
J & 26301.0368 +- 251.4464259406616 \\
K & 992 +- 11.759349675429672 \\
L & 1704.4 +- 10.134643624028467 \\
M & 13646 +- 6.642512495416339 \\
```

That's where I got with a bit of textual preprocessing.
From my point of view, it would make sense to round both the number as well as the error to one decimal place, so that the output would more or less be similar to this one:
```
A &   126.0 +-   0.5 \\
B &  3014.2 +-  35.5 \\
C &   115.9 +-   1.9 \\
D &  2859.9 +-  31.7 \\
E &  4560.4 +- 216.2 \\
F &   310.2 +-   3.0 \\
G & 11552.7 +-  44.0 \\
H &  4135.7 +-   8.2 \\
I &  4087.1 +- 106.4 \\
J & 26301.0 +- 251.4 \\
K &   992.0 +-  11.8 \\
L &  1704.4 +-  10.1 \\
M & 13646.0 +-  6.6 \\
```

The interpretation would be, taking line `C` for example: 
> The actual mean for series C lies between 114.0 and 117,8

Note that parenthesised numbers for uncertainties are uncommon in my area.

(hope this helps)
