### ISSUE TITLE
Rounding precision id greater given

### ISSUE THREAD

**Issue by parnmatt** [josephwright/siunitx#274]
If I have

``` latex
\sisetup{%
    round-mode=figures,%
    round-precision=4,%
}
```

and I used `\num{1.2}`, I really _do not want_ `1.200` printed. That is not the correct number of significant figures, and technically, it is a different number. For such a number, there are only 2 sig. fig. given, thus only 2 should be displayed. However for `\num{1.23456789}`, then it makes sense that `1.234` is printed.

You should only be able to subtract from the number of significant figures, not add to.

I know that this may be what some want, and I guess to preserve backwards compatibility, another option could be set something like, `round-max-precision=4`, which only rounds precision greater than 4, to 4.

**Comment by josephwright** [comment]
I think it's more accurate to say that the input `\num{1.2}` may or may not be equivalent to `\num{1.200}`. Some automated systems only print trailing digits if they are non-zero: the rounding system is there primarily for automated work in tabulars. In such places I would strongly suggest only using values of the same (display) accuracy if aligning.

All that said: I can see an argument for this. Probably rather than a separate option also needing a number of places, a clearer interface to me seems to be a switch `round-zero-fill` which turns on or off zero-filling.

**Comment by parnmatt** [comment]
with a default of `round-zero-fill=true` to preserve backwards compatibility. This certainly would be an alternative, and clearer interface.

:+1:

**Comment by parnmatt** [comment]
Has there been any progress in the implementation of the potential `round-zero` option you put forward here?

**Comment by josephwright** [comment]
This will be in v3: I've had another more-or-less equivalent request. I may back-port for v2: the code change is trivial ...
