### ISSUE TITLE
Double entries in index

### ISSUE THREAD

**Issue by samcarter8** [josephwright/siunitx#308]
There are some double entries in the index of the documentation, for example for `\DeclareSIPrefix` (see attached screen shot). The link of the first entry links to the title page (seems to be broken?) , the link of the second entry correctly links to page 12.

![screen shot 2017-06-12 at 16 47 49](https://user-images.githubusercontent.com/8226363/27039777-460ee95e-4f8f-11e7-8660-3b4db88560c5.png)

[version of the doc is `Released 2017/05/19` which is included in texlive 2017]

**Comment by josephwright** [comment]
Odd: I'll have to track down if this is 'me' or something from `l3doc` or whatever

**Comment by josephwright** [comment]
Right, the problem (or at least effect) comes from `l3doc`: a while ago it go adjusted so that `\cs` adds index entries. I need to look at that code and think what is the best mark-up to go for.

**Comment by josephwright** [comment]
I've had a look at the `l3doc` code and I think arguably the issue is there: it writes index entries in a similar but not identical way to `\SpecialIndexEntry`, which is where the problem fundamentally comes from. Rather than hack-fix it in `siunitx.dtx`, I'll see if we can sort it properly in `l3doc`.
