### ISSUE TITLE
Unit macro definition clashes with macro definitions not in preamble

### ISSUE THREAD

**Issue by cousteaulecommandant** [josephwright/siunitx#348]
According to the manual,
> The standard `siunitx` settings only create these abbreviations within the scope of the` \si` and
`\SI` functions, meaning that no clashes should occur

However, this causes an error (using siunitx.sty 2017/11/26 v2.7k):
```latex
\listfiles
\documentclass{article}
    \usepackage{siunitx}
    %~ \newcommand\A{letterA} % no error here in the preamble
\begin{document}
    \newcommand\A{letterA} % error here -- \A already defined
    10\,\si\A % with \si, I should see "A"
    10\,\A % without \si, I would see "letterA"
\end{document}
```
```
./Ttex.tex:6: LaTeX Error: Command \A already defined.
```
in other words, declaring a command named `\A` or any other siunitx abbreviation inside the document body causes an error (but not if the declaration is in the preamble).  I think a macro declaration like `\A` might be common enough for this to be a problem (I was using it as an auxiliary macro inside a table environment, and this error didn't show up until I upgraded to a newer siunitx that defines `\A`).  What do you think?

**Comment by josephwright** [comment]
The set up here hasn't changed since more-or-less day one. For various reasons, it is important that unit macros have some definition in the document body. At the same time, defining document commands should take place in the preamble. As such, `siunitx` delays creating unit macros until the start-of-document hook, but at that point the definitions have to be made.
