### ISSUE TITLE
(Proposal) Preventing empty number situation

### ISSUE THREAD

**Issue by Lionel-dS** [josephwright/siunitx#485]
Hi!

While migrating to v3, I faced an odd situation:
I must use `print-zero-exponent = false` and `print-unity-mantissa = false` since I'm dealing with standard quantities, scientific notation and orders of magnitude...
And with this setup, a simple quantity as `\qty{1}{\litre}` only displays "L".

I don't know if it is important in some cases to keep such behavior, so is it possible to add an option `prevent-empty-number`?

Thx for the great work on siunitx!

**Comment by josephwright** [comment]
I think I should treat this as a bug: v2 ignores `retain-unity-mantissa = false` if there's also no exponent part.

**Comment by lkkmpn** [comment]
After updating from 3.0.6 to 3.0.12, I noticed that `\num{1}` doesn't print anything anymore with `print-unity-mantissa = false`, while it used to print '1' before the update. I think this might be linked to the problem described by Lionel-dS, and based on the changes between 3.0.6 and 3.0.12, I guess it might have to do with the fix for #459 (although I haven't had time to actually check this).

**Comment by josephwright** [comment]
Fix coming up

**Comment by josephwright** [comment]
Fixed by e13866d9793268224c41bd1f5d217dcc19a4d2b9.
