### ISSUE TITLE
\micro is displayed wrong in LuaLaTeX and XeLaTeX if using T1 fonts with v3

### ISSUE THREAD

**Issue by jeanyvesb9** [josephwright/siunitx#582]
`\micro` is displayed as a ţ, instead of μ if using `\usepackage[T1]{fontenc}` and compiling on LuaLaTeX or XeLaTeX with `siunitx` v3 (it's fine with v2). It also works fine on v3 if compiling with pdflatex.

MWE:
```
  \documentclass{article}
  
  \usepackage[T1]{fontenc}
  \usepackage{siunitx}
  
  \begin{document}
  \SI{2}{\micro\meter}
  \end{document}
```

**Comment by josephwright** [comment]
For v3 I've taken a slightly harder line about using the correct font/input encoding setup. That means that for Unicode engines I assume UTF-8 encoded input. Using `T1` fonts with Unicode engines is not really correct, as some of the slots are not in the correct places for UTF-8 input. So this is essentially 'by design'.
