### ISSUE TITLE
Show asymmetric uncertainty as symmetric when upper and lower uncertainties are the same

### ISSUE THREAD

**Issue by kh296** [josephwright/siunitx#688]
If upper and lower values for an asymmetric uncertainty are the same, they're currently shown as superscript and subscript:

```
\num{20.01(2:2)} gives approximately the same as $20.01^{+0.02}{-0.02}$
```

There could perhaps be a package option to retain the current behaviour, or to  recognise automatically when the two uncertainties are the same, and show them as a symmetric uncertainty:

```
\num{20.01(2:2)} should give approximately the same as $20.01 \pm 0.02$
```

This could be useful, for example, when autogenerating tables of values and their uncertainties, as the user could use the syntax for asymmetric uncertainties in all cases, without needing to check whether lower and upper uncertainties are the same or different.

**Comment by Gerald-Meyers** [comment]
This is not necessarily always ideal, and in table environments I would want the upper and lower bounds to display separately. Perhaps as an option? Eg `always-display-uncertainty-separately=False` usually.

**Comment by josephwright** [comment]
@Gerald-Meyers  I'll definitely have this as an option and off as standard.

**Comment by kh296** [comment]
Having this as an option sounds good to me!  Thanks!

**Comment by josephwright** [comment]
OK, I've been thinking about this. There are two possible approaches

1. Normalise at the point of input, so that a two-part but symmetrical uncertainty is simply stored as a single value
2. Handle at the point of output (so a display setting)

Conceptually the two are not the same - I suspect (though I am not sure) that the major use case here is where conceptually two values should be kept, so handled in the second way.

**Comment by josephwright** [comment]
I've gone with `simplify-uncertainty` as a name: if there are better suggestions, they are welcome.
