### ISSUE TITLE
Poor formatting of `\kWh` when used in conjunction with `\per`

### ISSUE THREAD

**Issue by dbitouze** [josephwright/siunitx#752]
The following MCE shows that it is impossible to get right formatting for `\kWh`, defined as:

```latex
\siunitx_declare_unit:Nnn \kWh { \kilo \watt \hour }
  { inter-unit-product = }
```

when used in conjunction with `\per`:

```latex
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\qty{1}{\kWh}

\qty{1}{\kWh\per\kg}

\qty[inter-unit-product =]{1}{\kWh\per\kg}
\end{document}
```

![image](https://github.com/user-attachments/assets/a43a01db-9b3b-4897-88c6-ae0c8ed4eb6b)

**Comment by josephwright** [comment]
To-be-expected. The `\kWh` unit is set up to do the non-standard spacing people tend to want for the unit as-is. However, it's defined as `\kilo\watt\hour`, so when used in a combination it reverts to the standard spacing. If you want a 'fixed' spacing, you'll need to do
```latex
\DeclareSIUnit\kWh{kWh}
```
or similar so that it's not actually linked to the constituent units.

**Comment by josephwright** [comment]
This is covered in the manual in 'Special considerations for the `\kWh` unit'.

**Comment by dbitouze** [comment]
> This is covered in the manual in 'Special considerations for the `\kWh` unit'.

Ah,indeed, sorry to not have noticed!
