### ISSUE TITLE
\ohm does not work with mathastext package

### ISSUE THREAD

**Issue by csrabak** [josephwright/siunitx#757]
The issue goes around the problem with `mathrm` applied to a Greek letter.

The MWE follows:

```
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[LGRreek,defaultmathsizes]{mathastext}
\usepackage{siunitx}


\begin{document}

$\Omega$ works.

$\mathrm{\Omega}$ does not.

And \qty{1}{\ohm} also doesn't.

\end{document}
```

I sincerely don't know if this is the case of reporting as well the maintainer of `mathastext`package or not.

I do know the issue about the _correctness_ of using `mathrm` with mathematical symbols has a long history (I've seen the discussions in SO, even with Mittelbach's comments ), but at the state of the art right now what would be the adequate workaround.

**Comment by jfbu** [comment]
@csrabak  Hello `mathastext` author here. You could have tried with option `LGRgreek+` as documented  in `1.7.5 Special behavior of \mathrm, \mathbf, \mathit with Greek letters via the LGRgreek+ option`.  However, my siunitx is already updated to `3.3.23 2024-11-15` at my locale, so I do not know what would have happened with `\qty`, but the `\mathrm{\Omega}` would have "worked" (i.e. not modify the `\Omega` in your mwe).  Checkout `1.5 Math alphabets` for some related comments.

**Comment by josephwright** [comment]
>  However, my siunitx is already updated to `3.3.23 2024-11-15` at my locale, so I do not know what would have happened with `\qty`

I've special-cased `mathastext` to use `\text{\ensuremath{\Omega}}`, which 'escapes' from `\mathrm`.

**Comment by jfbu** [comment]
@josephwright Thanks for explanation. For the record, the reason `mathastext` + its option `LGRgreek` keeps the LaTeX default of a "variable family" `\Omega` is because the package provides `\mathgreekit`, `\mathgreekup`, `\mathgreekitbold` and `\mathgreekupbold` math alphabets.  Thus `\mathrm{\Omega}` as in OP mwe gives the logically expected result from `\Omega` having been declared to use its LGR slot position.  There is option `LGRgreek+`, but this was done reluctantly because it does not make sense to apply to Greek letters a math alphabet mapping to Latin encodings, so when we do  that, we change the semantics of original LaTeX  `\mathrm`, `\mathbf` etc...  (for non-Unicode engines).
